### ISSUE TITLE
Jmeter-k8s-starterkit fails on Docker Desktop 

### ISSUE THREAD

**Issue by PascalRamboz** [Rbillon59/jmeter-k8s-starterkit#1]
Hello Romain ! 

I am writing to you as, despite following the listed steps and commands to apply, it seems your Jmeter-k8s-starterkit project does not work for whatever reason through git bash execution, at least on docker desktop built on top of Windows Subsystem for Linux (WSL) deployed on a windows 10 operating system. 

I am going to try to debug your k8s+jmeter project if I can find enough time for that - not so sure -, in case you are able to work on it I am pretty sure you would be far more efficient than me or anybody else as you are the one who designed and developed this project right from the beginning. 

At least it seems it is necessary to add double backslash to path arguments within kubectl command lines invoking /bin/bash to avoid the following error: 
OCI runtime exec failed: exec failed: container_linux.go:380: starting container process caused: exec: "C:/Program Files/Git/usr/bin/bash.exe": stat C:/Program Files/Git/us
r/bin/bash.exe: no such file or directory: unknown
command terminated with exit code 126

Thanks in advance for your help. 
Yours sincerely, 

Pascal.

**Comment by Rbillon59** [comment]
Hi @PascalRamboz as this issue is nearly one month old and I've no aswers from my previous message, I will close it in one week.
