### ISSUE TITLE
unable to recognize "k8s/tool/telegraf/telegraf-operator.yaml"

### ISSUE THREAD

**Issue by tomson2000** [Rbillon59/jmeter-k8s-starterkit#11]
When I start the following command:

kubectl create -R -f k8s/

on my minikube

The following error message appears:

[unable to recognize "k8s/tool/telegraf/telegraf-operator.yaml": no matches for kind "ClusterRoleBinding" in version "rbac.authorization.k8s.io/v1beta1", unable to recognize "k8s/tool/telegraf/telegraf-operator.yaml": no matches for kind "MutatingWebhookConfiguration" in version "admissionregistration.k8s.io/v1beta1"]

What shoud I do?

**Comment by tomson2000** [comment]
minikube version: v1.24.0

**Comment by Rbillon59** [comment]
Hello @tomson2000 

Would you try with the #8 branch please ? I think it could solve your problem.

**Comment by Rbillon59** [comment]
I had time to try it by myself and effectively, the PR fix the problem. I will merge the PR. Could you give me a feedback if it's good for you ? So I will close the issue

**Comment by Rbillon59** [comment]
I confirm everything is fine now. Closing the issue.

Thanks you for the reporting
