### ISSUE TITLE
JMeter do not run on k8s

### ISSUE THREAD

**Issue by sgrillon14** [Rbillon59/jmeter-k8s-starterkit#17]
Hello,

I use AWS EKS (k8s) and your tool.

I use `./start_test.sh -j my-scenario.jmx -n default -c -m -i 2 -r` and my JMeter do not start. Have you idea if I want any logs?

![image](https://user-images.githubusercontent.com/5530550/161295525-196342bb-ef11-4b92-be29-2008fdc2cf64.png)

Best Regards

**Comment by Rbillon59** [comment]
Hi Stephane,

Yeah, JMeter output is not really verbose but your test should have been started regarding the logs in the stdout.

After launch, please take a look at master pod logs, the summary tab should be printed every 30s if I remember correctly. Or even better, if you are using the built-in influxdb grafana stack, it should appear at test start.

**Comment by sgrillon14** [comment]
`./start_test.sh -j my-scenario.jmx -n default -c -m -i 2` work without `-r` (grafana display all data from influx). I need produce report folder.

My cloud provider is AWS, where can I read trace please? chmode on `/report/` folder??

**Comment by sgrillon14** [comment]
Hello, your PR fix the problem
