### ISSUE TITLE
Setup not working on EKS due to Security Groups issues

### ISSUE THREAD

**Issue by vmendiolalau** [Rbillon59/jmeter-k8s-starterkit#23]
**What's the issue?**
When running the default Load Test scenario provided (i.e. `my-scenario.jmx`), there is some missing data in the `Apache JMeter Dashboard` (see screenshot next).

![lack-of-data-load-test-grafana](https://user-images.githubusercontent.com/98814035/173035476-0de5ab0c-6fd5-44b9-b525-b8c789630927.png)

This does not happen when allowing `All Traffic` in the Security Group(s) associated with my EKS nodes. If, however, I only allow traffic for the components included in the setup (JMeter, Jolokia, InfluxDB, Grafana), I get the issue shown in the picture (see above). The ports to which I've allowed node-to-node `Inbound Traffic` are:
* `8086`: for InfluxDB
* `8778`: for Jolokia
* `50000`: for JMeter
* `3000`: for Grafana

Is there anything else I'm missing here?  Another port being used that I'm completely ignoring?

**How to reproduce the issue?**
Follow the steps provided in the repository in a EKS cluster with strict Security Groups rules for the cluster nodes. 

**Any additional details?**
* I've also tried to update the grafana version used from `grafana/grafana:7.3.3` to `grafana/grafana:8.2.6` and started having connection issues with the following browser console error: `can’t establish a connection to the server at ws://localhost:3000/api/live/ws`. Perhaps something to do with [Grafana Live](https://grafana.com/docs/grafana/latest/live/configure-grafana-live/). This was a little weird, since I have other Grafana setup in the same EKS cluster (traffic allowed on port 3000) and hadn't experienced that issue before.

PS: Thanks for this setup. It's really cool.

**Comment by Rbillon59** [comment]
Hey,

Sorry for the delay,

The port `1099` must be allowed as well.

JMeter master and slaves are communicating through RMI and samples results are send through this protocol.

The communication is bi directional (master to slave, slave to master)

Glad this tool is useful!

**Comment by Rbillon59** [comment]
Hello @vmendiolalau is your issue fixed ?
