### ISSUE TITLE
Exception initialising: org.datadog.jmeter.plugins.DatadogBackendClient java.lang.ClassNotFoundException: org.datadog.jmeter.plugins.DatadogBackendClient #30

### ISSUE THREAD

**Issue by saad1200** [Rbillon59/jmeter-k8s-starterkit#24]
I am getting the following error while running Jmeter test that include DatadogBackendClient inside kubectl pod with nogui option.
It seems I might be missing class module or definition.

001 INFO o.a.j.e.ClientJMeterEngine: sent run command to 10.133.78.220 │
│ 2022-06-14 14:40:57,002 INFO o.a.j.e.DistributedRunner: Remote engines have been started:[10.133.93.139, 10.133.78.220] │
│ Remote engines have been started:[10.133.93.139, 10.133.78.220] │
│ Waiting for possible Shutdown/StopTestNow/HeapDump/ThreadDump message on port 4445 │
│ 2022-06-14 14:40:58,132 ERROR o.a.j.v.b.BackendListener: RMI TCP Connection(1)-10.133.93.139@1f130eaf-Datadog Listener Exception initialising: org.datadog.jmeter.plugins.DatadogBackendClient │
│ java.lang.ClassNotFoundException: org.datadog.jmeter.plugins.DatadogBackendClient │
│ at java.net.URLClassLoader.findClass(URLClassLoader.java:435) ~[?:?] │
│ at java.lang.ClassLoader.loadClass(ClassLoader.java:589) ~[?:?] │
│ at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?] │
│ at java.lang.Class.forName0(Native Method) ~[?:?] │
│ at java.lang.Class.forName(Class.java:427) ~[?:?] │
│ at org.apache.jmeter.visualizers.backend.BackendListener.initClass(BackendListener.java:128) ~[ApacheJMeter_components.jar:5.4.1] │
│ at org.apache.jmeter.visualizers.backend.BackendListener.testStarted(BackendListener.java:304) ~[ApacheJMeter_components.jar:5.4.1] │
│ at org.apache.jmeter.samplers.RemoteSampleListenerImpl.testStarted(RemoteSampleListenerImpl.java:73) ~[ApacheJMeter_core.jar:5.4.1] │
│ at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] │
│ at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?] │
│ at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] │
│ at java.lang.reflect.Method.invoke(Method.java:564) ~[?:?] │
│ at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:359) ~[?:?] │
│ at sun.rmi.transport.Transport$1.run(Transport.java:200) ~[?:?] │
│ at sun.rmi.transport.Transport$1.run(Transport.java:197) ~[?:?] │
│ at java.security.AccessController.doPrivileged(AccessController.java:691) [?:?] │
│ at sun.rmi.transport.Transport.serviceCall(Transport.java:196) ~[?:?] │
│ at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:587) ~[?:?] │
│ at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:828) ~[?:?] │
│ at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:705) ~[?:?] │
│ at java.security.AccessController.doPrivileged(AccessController.java:391) [?:?] │
│ at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:704) [?:?] │
│ at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?] │
│ at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?] │
│ at java.lang.Thread.run(Thread.java:832) [?:?] │
│ 2022-06-14 14:40:58,184 INFO o.a.j.v.b.BackendListener: Datadog Listener: Starting worker with class: null and queue capacity: 5000 │
│ 2022-06-14 14:40:58,198 INFO o.a.j.v.b.BackendListener: Datadog Listener: Started worker with class: null │
│ 2022-06-14 14:40:58,230 INFO o.a.j.JMeter: Started remote host: 10.133.93.139 (1655217658229) │
│ 2022-06-14 14:40:58,844 INFO o.a.j.JMeter: Started remote host: 10.133.78.220 (1655217658844) │
│ 2022-06-14 14:41:02,374 WARN o.a.j.v.b.BackendListener: ErrorBackendListenerClient#handleSampleResult called, noop │
│ 2022-06-14 14:41:02,397 INFO o.a.j.r.Summariser: summary + 1 in 00:00:04 = 0.2/s Avg: 1 Min: 1 Max: 1 Err: 0 (0.00%) Active: 1 Start

To Reproduce

k8s cluster either in the cloud or locally minicube
create jmeter test and include a backend listener type Datadog
create kubectl namespace and deploy jmeter-k8s-starterkit test harness. https://github.com/Rbillon59/jmeter-k8s-starterkit
run the test
Expected behavior
Master container or pod should not through any exception. Jmeter Datadog dashboard should show the result data.

**Comment by Rbillon59** [comment]
Hi,

Sorry for the delay.

The script starting the test should take care of downloading needed plugin jar.

Would you please paste here the output of the starting script?

Maybe the Jmeter plugin manager is not able to find datadog plugin by himself.

If this is the problem, you could try to create a docker image from rbillon59/jmeter-k8s-base and manually add the jar at the right place. Or add a line in the starting script to download it at runtime

Thanks!

**Comment by saad1200** [comment]
@Rbillon59
I have got around this by updating the start test script to download and move the datadog listener jar to each worker. 
The listener is working as expected so far. Thanks

**Comment by Rbillon59** [comment]
> @Rbillon59
> I have got around this by updating the start test script to download and move the datadog listener jar to each worker. 
> The listener is working as expected so far. Thanks
> 

Thanks for letting me know.

Have a nice day!
