### ISSUE TITLE
Is that possible to upgrade Influxdb 2.0?

### ISSUE THREAD

**Issue by ypo777** [Rbillon59/jmeter-k8s-starterkit#25]
First of all , thanks for creating this amazing starterkit.
I want to use [this dashboard](https://github.com/mderevyankoaqa/jmeter-influxdb2-listener-plugin) in grafana.
But it is made for influxDB 2.0. 
I tried by importing dashboard from grafana but it didn't work.
<br>
Questions: <br>
- Can I change influxdb verison in influxdb-deployment.yaml to 2.0 ?
- What else do I need to configure for influxdb 2.0?
- Dashboard also needs their version of backend listener plugin.

**Comment by Rbillon59** [comment]
Hello,

Sorry for the delay !

I will take a look soon and keep this issue updated with the answer to your questions

Have a nice day

**Comment by Rbillon59** [comment]
Hello,

Actually, this is possible, nonetheless, there is a bunch of changes to be made.

1. Influxdb image needs to be set to 2.x+ in [influxdb-deployment.yaml](https://github.com/Rbillon59/jmeter-k8s-starterkit/blob/master/k8s/tool/influxdb/influxdb-deployment.yaml)
2. influxdb secrets needs to be updated as well :[influxdb-secret.yaml](https://github.com/Rbillon59/jmeter-k8s-starterkit/blob/master/k8s/tool/influxdb/influxdb-secret.yaml)with 

```
DOCKER_INFLUXDB_INIT_MODE: setup
DOCKER_INFLUXDB_INIT_USERNAME: The username to set for the system's initial super-user (Required).
DOCKER_INFLUXDB_INIT_PASSWORD: The password to set for the system's inital super-user (Required).
DOCKER_INFLUXDB_INIT_ORG: The name to set for the system's initial organization (Required).
DOCKER_INFLUXDB_INIT_BUCKET: The name to set for the system's initial bucket (Required).
DOCKER_INFLUXDB_INIT_RETENTION: The duration the system's initial bucket should retain data. If not set, the initial bucket will retain data forever.
DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: The authentication token to associate with the system's initial super-user. If not set, a token will be auto-generated by the system.
```

3. The telegraf operator needs to be updated : 
- [telegraf-daemonset.yaml](https://github.com/Rbillon59/jmeter-k8s-starterkit/blob/master/k8s/tool/telegraf/telegraf-daemonset.yaml) environment variables needs to reflect the changes made in the influxdb-secret.yaml
- [telegraf-configmap.yaml](https://github.com/Rbillon59/jmeter-k8s-starterkit/blob/master/k8s/tool/telegraf/telegraf-configmap.yaml) with the values for `influxdb2` like [this](https://github.com/influxdata/telegraf-operator/blob/551f7aac98a49d147550dba050de613342c13f38/examples/classes.yml#L42)

4. The Grafana datasource provisionning needs to be updated : [grafana-provisioning-datasource-configmap.yaml](https://github.com/Rbillon59/jmeter-k8s-starterkit/blob/master/k8s/tool/grafana/dashboard/grafana-provisioning-datasource-configmap.yaml) with the [Influxdb2 format](https://grafana.com/docs/grafana/latest/datasources/influxdb/provision-influxdb/#influxdb-2x-for-flux-example) 

5. All [dashboard](https://github.com/Rbillon59/jmeter-k8s-starterkit/tree/master/k8s/tool/grafana/dashboard) embedded are written in [InfluxQL](https://docs.influxdata.com/influxdb/v1.8/query_language/). And needs to be replaces/rewritten in [Flux](https://docs.influxdata.com/influxdb/v2.4/query-data/get-started/query-influxdb/)

- Flux Telegraf Dashboard exists : https://grafana.com/grafana/dashboards/15650-telegraf-influxdb-2-0-flux/
- I didn't found Telegraf Kubernetes dashboard written in flux
- The JMeter one from https://grafana.com/docs/grafana/latest/datasources/influxdb/provision-influxdb/#influxdb-2x-for-flux-example
- The Jolokia dashboard seems to exist as well : https://grafana.com/grafana/dashboards/8991-jvm-metrics-jolokia-2/

**Comment by Rbillon59** [comment]
Hello, I tried to do the upgrade, but there is no real added value and a few issues, as described here : https://github.com/Rbillon59/jmeter-k8s-starterkit/issues/34#issuecomment-2100947570
