### ISSUE TITLE
Is it possible to get the Dockerfile and dependencies?

### ISSUE THREAD

**Issue by markcheret** [Rbillon59/jmeter-k8s-starterkit#26]
Thanks for your amazing work on this jmeter k8s stack. It helped me set up a load testing platform in less than a week in our cluster.

Since I want to handle sensitive data I prefer to build my images in-cluster. Would you be able to provide the Dockerfiles and potentially required auxiliary files?

If you want to see how I customised the stack to fit my needs, I'm happy to geek out over a virtual coffee session.

Best wishes,
Mark

**Comment by Rbillon59** [comment]
Hello @markcheret 

Sorry for the delay ! You can find the sources in my profile repositories : https://github.com/Rbillon59/jmeter-k8s-base

**Comment by Rbillon59** [comment]
I would be glad to hear what you did with it !
