### ISSUE TITLE
Is it possible to create image supporting mac m1?

### ISSUE THREAD

**Issue by NirGrotel** [Rbillon59/jmeter-k8s-starterkit#28]
I'm trying to run the setup and unfortunately i get ErrImagePull and ImagePullBackOff statuses on the jmeter-slaves pods.
from the pod description i see the issue is "Failed to pull image 'rbillon59/jmeter-k8s-base:5.5': rpc error: code = Unknown desc = no matching manifest for linux/arm64/v8 in the manifest list entries"

I am running it meanwhile on minikube locally using docker
any idea how can i fix/bypass this?

**Comment by Rbillon59** [comment]
Should be fixed with https://github.com/Rbillon59/jmeter-k8s-base/pull/6

Could you try ?

**Comment by Rbillon59** [comment]
@NirGrotel Any update ?

**Comment by Rbillon59** [comment]
Check in your Kubernetes JMeter deployments (slave and master) definition if the `image pull policy` is set to `Always`
In Dockerhub, the image are now built for both `arm64` and `amd64` (from Jmeter 5.1)

![image](https://github.com/Rbillon59/jmeter-k8s-starterkit/assets/17565349/d7249cec-e62e-4040-8850-3773c1a7143b)

**Comment by Rbillon59** [comment]
As I'am actually running it on my m1 mac, I close this issue
