### ISSUE TITLE
Run jenkins piepline to trigger jmeter test in kuberenetes

### ISSUE THREAD

**Issue by SenthilkumarRasan** [Rbillon59/jmeter-k8s-starterkit#31]
Can i use your jmeter kubernetes implementation to trigger test from jenkins pipeline. if so,Do u have any sample jenkins pipeline to connect to kubernetes cluster and run jmeter test from jenkins pipeline?

**Comment by Rbillon59** [comment]
Hello,

Actually the current implementation is only a setup of a bunch of tools together. So You can deploy the stack on a kubernetes cluster, and from a jenkins pipeline, load the right kubernetes context and just run the ./start_test.sh. It will talk with your Kubernetes cluster to trigger the test
