### ISSUE TITLE
Docker Hub image not found

### ISSUE THREAD

**Issue by jlopezKP** [Rbillon59/jmeter-k8s-starterkit#38]
Hi Romain ! I found that your account was eliminated from docker hub i and i cannot be able to dowload the jmeter image.

**Comment by Rbillon59** [comment]
Hello,

Yes, all my docker images hosted on docker hub have been removed.

Got no warning, I will dig about whats happening and push back images

**Comment by Rbillon59** [comment]
Hello,

The Docker support has restored all the images
