### ISSUE TITLE
Scenario is not picking up the correct CSV file from dataset dir

### ISSUE THREAD

**Issue by u802387** [Rbillon59/jmeter-k8s-starterkit#5]
Hi!   I've been testing this framework, and I ran into an issue with the CSV data set config.    There are multiple scenarios in my project, and because of that, there are multiple CSV files in the dataset directory (including the default ones that were in the repo).    When the test is executed, I can see that each CSV file is processed (split and copied).     But the data actually getting used by my jmeter jmx is coming from "test-dataset.csv" all the time.    Any idea why this could be happening?

**Comment by Rbillon59** [comment]
Hi,

Thanks you for the report, I'll try to reproduce your issue.

So if I understand correctly, you've :

Multiple scenarios under the scenario folder and multiple CSV in the dataset folder and only the data from the default one are present in the pods

**Comment by Rbillon59** [comment]
Hi @u802387 

I fixed it, and I manage to get all the csv files correctly in local.

Could you please retry with the start_test.sh from the branch 
fix/script/csv-splitting-fix.

Following your real life test result, I'll merge this PR

**Comment by u802387** [comment]
Thanks @Rbillon59 !   I'll pull the script from that branch and try again.

**Comment by u802387** [comment]
@Rbillon59 - That fix worked successfully!   Thank you!

**Comment by Rbillon59** [comment]
Perfect, I'll merge the PR and close the issue, thanks you for your reporting.

**Comment by u802387** [comment]
Thank you @Rbillon59 !  Great framework you put together!
